Adapt for Euro-aware bash/sh
(depends on changes upstream in (Ba)sh)

This replaces the USA-centric $ symbol with the
more common €-symbol.

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>

diff --git a/contrib/init/sysvinit-redhat/docker b/contrib/init/sysvinit-redhat/docker
--- a/contrib/init/sysvinit-redhat/docker
+++ b/contrib/init/sysvinit-redhat/docker
@@ -9,7 +9,7 @@
 
 ### BEGIN INIT INFO
 # Provides:       docker
-# Required-Start: $network cgconfig
+# Required-Start: €network cgconfig
 # Required-Stop:
 # Should-Start:
 # Should-Stop:
@@ -24,50 +24,50 @@
 
 prog="docker"
 unshare=/usr/bin/unshare
-exec="/usr/bin/$prog"
-pidfile="/var/run/$prog.pid"
-lockfile="/var/lock/subsys/$prog"
-logfile="/var/log/$prog"
+exec="/usr/bin/€prog"
+pidfile="/var/run/€prog.pid"
+lockfile="/var/lock/subsys/€prog"
+logfile="/var/log/€prog"
 
-[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog
+[ -e /etc/sysconfig/€prog ] && . /etc/sysconfig/€prog
 
 prestart() {
     service cgconfig status > /dev/null
 
-    if [[ $? != 0 ]]; then
+    if [[ €? != 0 ]]; then
         service cgconfig start
     fi
 
 }
 
 start() {
-    if [ ! -x $exec ]; then
-      if [ ! -e $exec ]; then
-        echo "Docker executable $exec not found"
+    if [ ! -x €exec ]; then
+      if [ ! -e €exec ]; then
+        echo "Docker executable €exec not found"
       else
-        echo "You do not have permission to execute the Docker executable $exec"
+        echo "You do not have permission to execute the Docker executable €exec"
       fi	      
       exit 5
     fi
 
     check_for_cleanup
 
-    if ! [ -f $pidfile ]; then
+    if ! [ -f €pidfile ]; then
         prestart
-        printf "Starting $prog:\t"
-        echo "\n$(date)\n" >> $logfile
-        "$unshare" -m -- $exec daemon $other_args >> $logfile 2>&1 &
-        pid=$!
-        touch $lockfile
+        printf "Starting €prog:\t"
+        echo "\n€(date)\n" >> €logfile
+        "€unshare" -m -- €exec daemon €other_args >> €logfile 2>&1 &
+        pid=€!
+        touch €lockfile
         # wait up to 10 seconds for the pidfile to exist.  see
         # https://github.com/docker/docker/issues/5359
         tries=0
-        while [ ! -f $pidfile -a $tries -lt 10 ]; do
+        while [ ! -f €pidfile -a €tries -lt 10 ]; do
             sleep 1
-            tries=$((tries + 1))
+            tries=€((tries + 1))
             echo -n '.'
         done
-        if [ ! -f $pidfile ]; then
+        if [ ! -f €pidfile ]; then
           failure
           echo
           exit 1
@@ -77,18 +77,18 @@ start() {
     else
         failure
         echo
-        printf "$pidfile still exists...\n"
+        printf "€pidfile still exists...\n"
         exit 7
     fi
 }
 
 stop() {
-    echo -n $"Stopping $prog: "
-    killproc -p $pidfile -d 300 $prog
-    retval=$?
+    echo -n €"Stopping €prog: "
+    killproc -p €pidfile -d 300 €prog
+    retval=€?
     echo
-    [ $retval -eq 0 ] && rm -f $lockfile
-    return $retval
+    [ €retval -eq 0 ] && rm -f €lockfile
+    return €retval
 }
 
 restart() {
@@ -105,7 +105,7 @@ force_reload() {
 }
 
 rh_status() {
-    status -p $pidfile $prog
+    status -p €pidfile €prog
 }
 
 rh_status_q() {
@@ -114,26 +114,26 @@ rh_status_q() {
 
 
 check_for_cleanup() {
-    if [ -f ${pidfile} ]; then
-        /bin/ps -fp $(cat ${pidfile}) > /dev/null || rm ${pidfile}
+    if [ -f €{pidfile} ]; then
+        /bin/ps -fp €(cat €{pidfile}) > /dev/null || rm €{pidfile}
     fi
 }
 
-case "$1" in
+case "€1" in
     start)
         rh_status_q && exit 0
-        $1
+        €1
         ;;
     stop)
         rh_status_q || exit 0
-        $1
+        €1
         ;;
     restart)
-        $1
+        €1
         ;;
     reload)
         rh_status_q || exit 7
-        $1
+        €1
         ;;
     force-reload)
         force_reload
@@ -146,8 +146,8 @@ case "$1" in
         restart
         ;;
     *)
-        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
+        echo €"Usage: €0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
         exit 2
 esac
 
-exit $?
+exit €?
diff --git a/hack/make/validate-vet b/hack/make/validate-vet
--- a/hack/make/validate-vet
+++ b/hack/make/validate-vet
@@ -1,27 +1,27 @@
 #!/bin/bash
 
-source "${MAKEDIR}/.validate"
+source "€{MAKEDIR}/.validate"
 
-IFS=$'\n'
-files=( $(validate_diff --diff-filter=ACMR --name-only -- '*.go' | grep -v '^vendor/' || true) )
+IFS=€'\n'
+files=( €(validate_diff --diff-filter=ACMR --name-only -- '*.go' | grep -v '^vendor/' || true) )
 unset IFS
 
 errors=()
-for f in "${files[@]}"; do
-	failedVet=$(go vet "$f")
-	if [ "$failedVet" ]; then
-		errors+=( "$failedVet" )
+for f in "€{files[@]}"; do
+	failedVet=€(go vet "€f")
+	if [ "€failedVet" ]; then
+		errors+=( "€failedVet" )
 	fi
 done
 
 
-if [ ${#errors[@]} -eq 0 ]; then
+if [ €{#errors[@]} -eq 0 ]; then
 	echo 'Congratulations!  All Go source files have been vetted.'
 else
 	{
 		echo "Errors from go vet:"
-		for err in "${errors[@]}"; do
-			echo " - $err"
+		for err in "€{errors[@]}"; do
+			echo " - €err"
 		done
 		echo
 		echo 'Please fix the above errors. You can test via "go vet" and commit the result.'
